Repository boostcamp-2020/Project17-B-Map, pull requests merged in 2020-12, with the labels that each got.

#58 [Feature/coredata] CoreData throws제거 후 Result 타입으로 변경
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaBTests.xcscheme
  BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Clustering/LinkedListTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/ClusteringTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/KMeansTest.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: CoreData, 🛠Refactoring

#59 fix : convexHull 가끔 선을 안그리던 버그 수정
  BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/ConvexHull.swift
Labels: bug

#69 [Feature/point to poi] Clustering 타입 LatLng -> POI 변경
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/BoostClusteringMaB.xcdatamodeld/BoostClusteringMaB.xcdatamodel/contents
  BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/Cluster.swift
  BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/KMeans/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/Models/ManagedPOI+CoreDataProperties.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/Models/POI.swift
Labels: Clustering, CoreData, 🛠Refactoring

#67 [feature/fix animation] 애니메이션 수정
  BoostClusteringMaB/BoostClusteringMaB/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/MarkerAnimateController.swift
  BoostClusteringMaB/BoostClusteringMaB/Persistence/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: Animation

#70 [Feature/vc and clustering refactor] ViewController를 VIP패턴으로 코드 정리
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/UIColor+RandomColor.swift
  BoostClusteringMaB/BoostClusteringMaB/KMeans/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainPresenter.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/extension/NMFMarker+ImageView.swift
  BoostClusteringMaB/BoostClusteringMaB/extension/NMFPolygonOverlay+.swift
  BoostClusteringMaB/BoostClusteringMaB/extension/UIColor+RandomColor.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CSVParserTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/ClusteringTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: 🛠Refactoring

#78 [feat/clustering_kRange] : kRange 범위 수정
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering

#77 [feature/address api] AddressAPI
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaBTests.xcscheme
  BoostClusteringMaB/BoostClusteringMaB.xcworkspace/xcshareddata/xcschemes/BoostClusteringMaBTests.xcscheme
  BoostClusteringMaB/BoostClusteringMaB/BoostClusteringMaB.xcdatamodeld/BoostClusteringMaB.xcdatamodel/contents
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataProperties.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/POI.swift
  BoostClusteringMaB/BoostClusteringMaB/Info.plist
  BoostClusteringMaB/BoostClusteringMaB/Models/Geocoding.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/Main.storyboard
  BoostClusteringMaB/BoostClusteringMaB/Util/AddressAPI.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/JsonParser.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
Labels: UI

#74 [Fix/poi point] POI를 추가할때 마우스 위치 조정
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering, UI

#73 [feature/coredata_add_point] 마커를 눌렀을 때 CoreData와 연동하여 추가하거나 삭제하는 기능 추가
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/AlertType.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: CoreData, UI

#79 [Feature/unit test] Unit Test를 위한 AddressAPI, JSONParser Protocol 생성
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/AddressAPI.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/JsonParser.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
Labels: bug

#81 [Feature/convex hull bug] ConvexHull 중복데이터 처리
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/ConvexHull.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Clustering/ConvexHullTests.swift
Labels: UI, bug

#80 [fix/reusable_cell_image_download_fail] 디테일뷰 셀의 이미지가 여러번 로드되는 문제 수정
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/UIImageView+loadImage.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/ImageDownloader.swift
Labels: UI, bug

#82 [Feature/detail view controller] 디테일뷰를 위 아래로 드래그해서 크기 조절할 수 있다
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionReusableView.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/Main.storyboard
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
Labels: UI

#84 [Feature/cluster click reload] Cell 클릭 시 확대, Cluster 클릭 시 cell 데이터 update
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/ConvexHull.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/CGPoint+Distance.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/String+Bundle.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/JsonParser.swift
Labels: Clustering, UI

#83 [Develop] 3주차 코드프리징
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaBTests.xcscheme
  BoostClusteringMaB/BoostClusteringMaB.xcworkspace/xcshareddata/xcschemes/BoostClusteringMaBTests.xcscheme
  BoostClusteringMaB/BoostClusteringMaB/Assets.xcassets/NaverColor.colorset/Contents.json
  BoostClusteringMaB/BoostClusteringMaB/BoostClusteringMaB.xcdatamodeld/BoostClusteringMaB.xcdatamodel/contents
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/ConvexHull.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataProperties.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/POI.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/CGPoint+Distance.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/String+Bundle.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/UIImageView+loadImage.swift
  BoostClusteringMaB/BoostClusteringMaB/Info.plist
  BoostClusteringMaB/BoostClusteringMaB/Models/Geocoding.swift
  BoostClusteringMaB/BoostClusteringMaB/NanumSquareRoundOTFEB.otf
  BoostClusteringMaB/BoostClusteringMaB/NanumSquareRoundOTFR.otf
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionReusableView.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/AlertType.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/LaunchScreen.storyboard
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/Main.storyboard
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Loading.storyboard
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/AddressAPI.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/ImageDownloader.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/JsonParser.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Clustering/ConvexHullTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: Animation, Clustering, CoreData, UI, bug, 👨‍💻TEST, 🛠Refactoring

#87 [Feature/cluster center] 클러스터 그려지는 위치 센터로 수정
  BoostClusteringMaB/BoostClusteringMaB/Models/LatLng.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
Labels: Clustering

#89 [Hotfix/memory managed poi] ManagedPOI 메모리에서 사라지지 않는 현상
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
Labels: bug

#90 [Feature/clustering operation] 클러스터링 계산이 누적되는거 수정
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaB.xcscheme
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
Labels: Clustering

#91 [Hotfix/memory leak] LoadViewController, marker.touchHandler memory에서 안 사라지는 문제
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/xcshareddata/xcschemes/BoostClusteringMaB.xcscheme
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: bug, 🔨 Memory

#97 [Hotfix/operation queue] OperationQueue 수정
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering, bug

#95 [feature/adjust marker image view] 클러스터 마커 동적 이미지 크기 / 애니메이션
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/MarkerAnimateController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
Labels: Animation, UI

#96 [feature/improving detailview] Detailview 개선
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: Animation, UI

#103 [feat : k_range] k 범위 조정
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
Labels: Clustering, bug

#104 [Feature/address_fetch_each_cell] DetailView의 주소를 각 셀마다 불러오도록 수정
  BoostClusteringMaB/BoostClusteringMaB/BoostClusteringMaB.xcdatamodeld/BoostClusteringMaB.xcdatamodel/contents
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataProperties.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/POI.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/AddressAPI.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
Labels: CoreData, 👨‍💻TEST, 🛠Refactoring

#106 [Feature/improving marker] 마커 터치
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Clustering/ClusteringProtocol.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/Extension/UIColor+.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainPresenter.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/ClusteringTests.swift
Labels: UI

#105 [Feature/detail view search] CollectionView수정, 검색기능 추가
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: UI

#107 [feature/improving marker] 클러스터 마커 이미지(뷰) 변경
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
Labels: Animation, UI

#109 [Hotfix/cluster optimization] 클러스터링 개선사항
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Cluster.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/Models/LatLng.swift
  BoostClusteringMaB/BoostClusteringMaB/Models/LinkedList.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Loading/LoadViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering

#110 [Hotfix/search text remove] 검색 기능 개선
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: UI

#124 [feature/improving_marker] 마커 이미지 뷰 / 애니메이션
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFMarker+.swift
  BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: Animation, UI

#125 [Feature/detail view size] 디테일뷰가 정상적으로 움직이지 않던 문제 수정
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
Labels: Animation, bug

#126 [Feature/detail view size] cancel 버튼이 비활성화(회색) 되어 있을 때도 눌리는 문제
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: bug

#127 [Feature/detail view result count] 검색 결과 갯수 표시하기
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionReusableView.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: UI

#128 [Feature/improving dot animation] Dot Animation 변경
  BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: UI

#130 [Fix] 애니메이션 시, 마커 사라짐
  BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
Labels: Animation

#132 [Hotfix/animation add remove bug] POI add, remove할 때 animation버그 수정
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/Extension/NMFCameraUpdate+.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainInteractor.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: bug

#135 [Hotfix/min kmeans] min K-Means 구하는 방식 변경
  BoostClusteringMaB/BoostClusteringMaB/Clustering/Clustering.swift
  BoostClusteringMaB/BoostClusteringMaB/Clustering/KMeans.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering

#136 [feature/improving marker] 마커 이미지 / 애니메이션 개선
  BoostClusteringMaB/BoostClusteringMaB/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerImageView.swift
Labels: Animation, UI

#139 [Feature/detail view fetch bounds] DetailView의 minimum 영역은 패치하지 않기
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Clustering, CoreData, UI

#140 [Feature/detailView_Button] DetailView up & down button
  BoostClusteringMaB/BoostClusteringMaB/Assets.xcassets/minimum.imageset/Contents.json
  BoostClusteringMaB/BoostClusteringMaB/Assets.xcassets/minimum.imageset/minimum.png
  BoostClusteringMaB/BoostClusteringMaB/Assets.xcassets/partial.imageset/Contents.json
  BoostClusteringMaB/BoostClusteringMaB/Assets.xcassets/partial.imageset/partial.png
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: UI

#142 [Hotfix/view_order] view 순서 재정의
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/DrawerMenu/DrawerController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Base.lproj/Main.storyboard
Labels: bug

#146 [Fix/detailview indicator] 디테일뷰의 인디케이터가 중앙에 오지 않던 문제 수정
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/Detail.storyboard
Labels: UI, bug

#148 [Hotfix/chore] 자잘한 오류 수정
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/DrawerMenu/DrawerController.swift
Labels: bug

#147 [Feature/fix intermittent animation error]
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
Labels: Animation, UI

#150 [Feature/delete unused] 사용하지 않는 코드 삭제
  BoostClusteringMaB/BoostClusteringMaB.xcodeproj/project.pbxproj
  BoostClusteringMaB/BoostClusteringMaB/CoreData/CoreDataLayer.swift
  BoostClusteringMaB/BoostClusteringMaB/CoreData/Models/ManagedPOI+CoreDataClass.swift
  BoostClusteringMaB/BoostClusteringMaB/Models/DrawerModels/LayerGroup.swift
  BoostClusteringMaB/BoostClusteringMaB/Models/LinkedList.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/View/DetailCollectionViewCell.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/Animations/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/Animations/MarkerAnimateController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Views/MarkerLayerFactory.swift
  BoostClusteringMaB/BoostClusteringMaB/Util/AddressAPI.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CSVParserTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Clustering/ConvexHullTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Clustering/LinkedListTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/CoreData/CoreDataTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/ClusteringTests.swift
  BoostClusteringMaB/BoostClusteringMaBTests/KMeans/KMeansTest.swift
  BoostClusteringMaB/BoostClusteringMaBTests/Mocks/CoreDataLayerMock.swift
Labels: 🛠Refactoring

#151 [hotfix/marker afterimage] 마커 잔상 문제
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/Animations/MainAnimationController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: Animation

#152 [Hotfix/touch and animation] 터치, 애니메이션 오류
  BoostClusteringMaB/BoostClusteringMaB/Scenes/Detail/DetailViewController.swift
  BoostClusteringMaB/BoostClusteringMaB/Scenes/MainView/MainViewController.swift
Labels: bug
